name: Repository Events
on:
  push:
  # We specify on what type of pull_requests our workflow will be execute
  pull_request:
    types: [opened, assigned, reopened]
  # We specify on what type of issues our workflow will be execute
  issues:
    types: [opened]

jobs:
  checkout-latest:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3