# Once this workflow will be completed, another workflow in 19-workflow-run.yml file will be executed.
# This is called nesting workflow. Github allows upto 3 level nesting.

name: Run workflow based on another workflow
on: [push]

jobs:
  checkout-latest:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3