name: Workflow Run
on:
  workflow_run:
    workflows: [Run workflow based on another workflow]
    # We can pass [completed, requested, in_progress] values in below 'types'
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because 'Run workflow based on another workflow' was completed"