# When you want to run a job multiple times with different variables, we use Matrix.

name: Matrix
on: [push]
jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15, 16]
    steps:
      # Below step will execute n times Job based on total no of values available in matrix variable 'node-version'
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v

