# We have Default and Custom Environment Variables
name: Environment Variable
on: [push]

jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV VAR
        # Below will be evaluate on runner machine, as this is ENV variable.
        run: echo $GITHUB_REF
      - name: Log Context VAR
        # Below will be evaluated by github action before sending workflow to runner machine.
        run: echo '${{ github.ref }}'