name: Simple Action
on: [push]
jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        # 'uses' is use to call action. Below is public action syntax. We can provide private action also.
        uses: actions/hello-world-javascript-action@main # username/action-name@<version/branch-name/commit-id>
        # 'with' key is use to pass parameters value when action receive any parameters.
        with:
          # 'who-to-greet' is parameter name, 'Pankaj' is parameter value. 
          who-to-greet: Pankaj
      - name: Log Greeting time
        # Previous action returns an output variable name as 'time'. we access that variable using below.
        run: echo "${{ steps.greet.outputs.time }}"