name: Checkout Action Example
on: [push]
jobs:
  checkout-action-example:
    runs-on: ubuntu-latest
    steps:
      - name: List File Before
        run: ls -a
      
      # This is main code to use Public Checkout Action.
      - uses: actions/checkout@v3 # username/action-name@<version/branch-name/commit-id>

      - name: List File After
        run: ls -a