name: Workflow commands
on: [push]

jobs:
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error Message
              run: echo "::error::This is error message"
            - name: Setting an debug Message
              run: echo "::debug::This is debug message"
            - name: Setting an warning Message
              run: echo "::warning::This is warning message"
            - name: Setting an notice Message
              run: echo "::notice::This is notice message"
            - name: Group of logs
              run: |
                 echo "::group::My group title"
                 echo "Inside group"
                 echo "::endgroup::"
            - name: Masking a Value
              run: echo "::add-mask::Secret String"
            - name: Echo a Secret
              run: echo "Secret String"
