name: Parallel & Dependent Job
on: [push]

jobs:
    echo-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View Software Version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        # 'needs' can be either a job id, or array of job ids
        needs: echo-job
        steps:
            - name: echo a string
              run: Write-Output "Windows String"