# Configuration variables(CV) are availables for all workflow under a REPO.
# Or Multiple REPO of under an organization(ORG).
# We never define CV in workflow files. We define in ORG/REPO/ENV level

name: Configuration Variables & Secret
on: [push]
jobs:
  log-vars:
    # ${{ vars }} This OBJ will have all ORG/REPO/ENV Varialbes
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: "production"
    env:
      # Make ORG/REPO/ENV level secrets as local env.
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      # Make ORG/REPO/ENV level variables as local env.
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I ran"
      
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"