# We can dynamically define environment variables by writing to specific file into runner machine.
# During the execution of workflow, runner machine generates some temp files.
# Those temp files can be used to perform certain actions. Like: Define ENV Variable
# GITHUB_ENV is default variable. which contain path to certain temp file, where we can write new ENV VAR

name: Set Dynamic ENV Vars
on: [push]
env:
  STATIC_ENV_VAR: Job Level but Static ENV
jobs:
  dynamic-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV Var
        # Now All below ENV will be available to subsequent steps, but not for current step.
        # We can override JOB Level ENV Variable.
        run: |
          echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
          echo "STATIC_ENV_VAR=$RANDOM" >> "$GITHUB_ENV"
      
      - name: Log ENV Var
        run: |
          echo $NEW_ENV_VAR
          echo $STATIC_ENV_VAR